### ISSUE TITLE
checkout greenkeeper.io ;)

### ISSUE THREAD

**Issue by tinnet** [victorparmar/npm-dependency-notifer#1]
https://greenkeeper.io

**Comment by victorparmar** [comment]
There is no way I am paying a cent for something so simple like this. I'm already done with the initial version, took me exactly 25 mins.

Adding the extra feature of sequential auto upgrade and run tests in some sort of a docker environment is not mind boggling either, about a day's worth of work imo.

**Comment by victorparmar** [comment]
@tinnet Here you go: https://github.com/victorparmar/npm-dependency-notifer/commit/95a18a5d53da2f6a6546755d6245b5705a72ed9e
